// design/components/canvas/service-node.tsx
'use client';

import { Handle, Position, type Node, type NodeProps } from '@xyflow/react';
import { GlobeIcon, HardDriveIcon } from 'lucide-react';
import { ServiceIcon } from '@/components/service/service-icon';
import { RuntimeBadge } from '@/components/status-badge';
import { serviceTypeLabel, type Service } from '@/lib/mock';
import { cn } from '@/lib/utils';

export type ServiceNodeType = Node<{ service: Service; dimmed: boolean }, 'service'>;

export function ServiceNode({ data, selected }: NodeProps<ServiceNodeType>) {
	const s = data.service;
	return (
		<div className={cn('w-64 transition-opacity', data.dimmed && 'opacity-45')}>
			<Handle type="target" position={Position.Left} className="!size-2 !border-0 !bg-transparent" isConnectable={false} />
			<div
				className={cn(
					'relative z-10 rounded-lg border bg-card transition-colors hover:border-foreground/25',
					selected && 'border-foreground/60 hover:border-foreground/60',
					s.status === 'failed' && !selected && 'border-destructive/50',
					s.status === 'progressing' && !selected && 'border-info/50'
				)}
			>
				<div className="space-y-2.5 p-3.5">
					<div className="flex items-start gap-2.5">
						<ServiceIcon type={s.type} className="mt-0.5 text-muted-foreground" />
						<div className="min-w-0 flex-1">
							<div className="truncate text-sm font-semibold">{s.name}</div>
							<div className="truncate font-mono text-[11px] text-muted-foreground">
								{s.source}
								{s.branch && <span className="text-muted-foreground/70"> · {s.branch}</span>}
							</div>
						</div>
					</div>
					<div className="flex items-center justify-between">
						<RuntimeBadge status={s.status} replicas={s.replicas} />
						<span className="text-[11px] text-muted-foreground">{serviceTypeLabel[s.type]}</span>
					</div>
				</div>
				{(s.domain || s.port) && (
					<div className="flex items-center gap-1.5 border-t px-3.5 py-2 text-[11px] text-muted-foreground">
						{s.domain ? (
							<>
								<GlobeIcon className="size-3 shrink-0" />
								<span className="truncate font-mono">{s.domain}</span>
							</>
						) : (
							<span className="font-mono">internal</span>
						)}
						{s.port && <span className="ml-auto shrink-0 font-mono">:{s.port}</span>}
					</div>
				)}
			</div>
			{s.volume && (
				<div className="mx-3 -mt-1 rounded-b-lg border border-t-0 bg-muted/60 px-3 pt-2.5 pb-2 text-[11px] text-muted-foreground">
					<div className="flex items-center gap-1.5">
						<HardDriveIcon className="size-3" />
						<span className="truncate font-mono">{s.volume.name}</span>
						<span className="ml-auto font-mono">{s.volume.size}</span>
					</div>
					<div className="mt-1.5 h-1 overflow-hidden rounded-full bg-border">
						<div
							className={cn('h-full rounded-full', s.volume.usedPct > 90 ? 'bg-destructive' : s.volume.usedPct > 70 ? 'bg-warning' : 'bg-primary')}
							style={{ width: `${s.volume.usedPct}%` }}
						/>
					</div>
				</div>
			)}
			<Handle type="source" position={Position.Right} className="!size-2 !border-0 !bg-transparent" isConnectable={false} />
		</div>
	);
}

// apps/console/app/components/service/board/ServiceNode.vue
<script setup lang="ts">
import { Handle, Position } from '@vue-flow/core';
import { Container, Network } from 'lucide-vue-next';
import type { Service, ServiceRuntime } from '~/utils/types';
import type { RuntimeStatus } from '~/components/base/RuntimeBadge.vue';
import { DATABASE_ENGINE_UI, isDatabaseEngine } from '~/utils/database-engines';

// Custom Vue Flow node. Vue Flow passes the node's `data` object through the slot props.
export interface ServiceNodeData {
	service: Service;
	runtime?: ServiceRuntime;
	isSelected: boolean;
	onSelect: (service: Service) => void;
}

const props = defineProps<{ data: ServiceNodeData }>();
const emit = defineEmits<{ select: [Service] }>();

const service = computed(() => props.data.service);
const runtime = computed(() => props.data.runtime);
const isDatabase = computed(() => isDatabaseEngine(service.value.type));
const image = computed(() => {
	const config = service.value.config;
	if ('version' in config) return `${DATABASE_ENGINE_UI[service.value.type as keyof typeof DATABASE_ENGINE_UI].label} ${config.version}`;
	if ('image' in config) return `${config.image}:${config.tag}`;
	if ('repoUrl' in config) return config.repoUrl;
	return 'Built from Dockerfile';
});
const typeLabel = computed(() => {
	if (isDatabase.value) return DATABASE_ENGINE_UI[service.value.type as keyof typeof DATABASE_ENGINE_UI].label;
	if (service.value.type === 'dockerfile') return 'Dockerfile';
	if (service.value.type === 'public-repo') return 'Git';
	if (service.value.type === 'private-repo') return 'Git (SSH)';
	return 'Docker';
});
// Datastores use the database icon as a subtle signal rather than a colour change.
const nodeIcon = computed(() => (isDatabase.value ? DATABASE_ENGINE_UI[service.value.type as keyof typeof DATABASE_ENGINE_UI].icon : Container));
</script>

<template>
	<div
		:class="[
			'group/node relative w-64 cursor-pointer rounded-lg border bg-background p-3 text-left shadow-sm transition hover:shadow-md',
			data.isSelected ? 'border-primary ring-2 ring-primary/20' : 'hover:border-primary/50'
		]"
		@click="emit('select', service)"
	>
		<Handle
			id="target-left"
			type="target"
			:position="Position.Left"
			:connectable="false"
			class="pointer-events-none !size-2 !border-0 !bg-transparent opacity-0"
		/>
		<Handle
			id="target-right"
			type="target"
			:position="Position.Right"
			:connectable="false"
			class="pointer-events-none !size-2 !border-0 !bg-transparent opacity-0"
		/>
		<Handle
			id="source-left"
			type="source"
			:position="Position.Left"
			:connectable="false"
			class="pointer-events-none !size-2 !border-0 !bg-transparent opacity-0"
		/>
		<Handle
			id="source-right"
			type="source"
			:position="Position.Right"
			:connectable="false"
			class="pointer-events-none !size-2 !border-0 !bg-transparent opacity-0"
		/>

		<div class="flex items-start gap-3">
			<span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary ring-1 ring-primary/15">
				<component :is="nodeIcon" class="size-5" />
			</span>
			<div class="min-w-0 flex-1">
				<div class="flex items-center gap-2">
					<h3 class="truncate text-sm font-semibold">{{ service.name }}</h3>
					<Badge variant="secondary">{{ typeLabel }}</Badge>
				</div>
				<p class="mt-1 truncate font-mono text-xs text-muted-foreground">{{ image }}</p>
				<RuntimeBadge
					:status="(runtime?.status ?? 'unknown') as RuntimeStatus"
					:ready-replicas="runtime?.readyReplicas"
					:desired-replicas="runtime?.desiredReplicas"
					class="mt-2"
				/>
				<div class="mt-2.5 flex items-center gap-2 text-xs text-muted-foreground">
					<Network class="size-3.5" />
					<span>{{ service.config.containerPort ? `:${service.config.containerPort}` : 'No port' }}</span>
					<span class="text-muted-foreground/40">·</span>
					<span>{{ service.config.env.length }} vars</span>
				</div>
			</div>
		</div>
	</div>
</template>
