// apps/console/components/page-header.tsx
import { cn } from '@/lib/utils';

export function PageHeader({
	title,
	description,
	actions,
	eyebrow,
	className
}: {
	title: React.ReactNode;
	description?: React.ReactNode;
	actions?: React.ReactNode;
	eyebrow?: React.ReactNode;
	className?: string;
}) {
	return (
		<div className={cn('flex flex-wrap items-end justify-between gap-4', className)}>
			<div className="min-w-0 space-y-1">
				{eyebrow && <div className="text-xs text-muted-foreground">{eyebrow}</div>}
				<h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
				{description && <p className="text-sm text-muted-foreground">{description}</p>}
			</div>
			{actions && <div className="flex items-center gap-2">{actions}</div>}
		</div>
	);
}

// apps/console/app/components/base/PageHeader.vue
<script setup lang="ts">
// Shared page header: title + optional description + right-aligned actions, with one consistent
// title-to-subtitle rhythm. Use the #breadcrumb slot above the title (project detail) and #actions on the right.
defineProps<{ title?: string; description?: string }>();
</script>

<template>
	<div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
		<div class="min-w-0">
			<slot name="breadcrumb" />
			<h1 class="text-2xl font-semibold tracking-tight">
				<slot name="title">{{ title }}</slot>
			</h1>
			<p v-if="description || $slots.description" class="mt-1.5 text-sm text-muted-foreground">
				<slot name="description">{{ description }}</slot>
			</p>
		</div>
		<div v-if="$slots.actions" class="flex shrink-0 items-center gap-2">
			<slot name="actions" />
		</div>
	</div>
</template>
