// apps/console/app/(auth)/auth/accept/page.tsx
import type { Metadata } from 'next';
import { AcceptInviteForm } from '@/features/auth/accept-invite-form';
import { InvalidLink } from '@/features/auth/invalid-link';
import { firstParam } from '@/lib/search-params';

export const metadata: Metadata = { title: 'Accept your invite' };

export default async function AcceptPage({ searchParams }: PageProps<'/auth/accept'>) {
	const token = firstParam((await searchParams).token);
	if (!token)
		return (
			<InvalidLink
				title="Invalid invite link"
				description="This link is missing its token. Ask an admin to resend the invite."
				tagline="Invites expire after seven days."
				action={{ href: '/auth/login', label: 'Back to sign in' }}
			/>
		);
	return <AcceptInviteForm token={token} />;
}

// apps/console/app/pages/auth/accept.vue
<script setup lang="ts">
definePageMeta({ layout: 'auth' });

const token = useRoute().query.token;
const tokenStr = typeof token === 'string' ? token : null;
</script>

<template>
	<AuthShell tagline="Join your team on kubwave">
		<CardHeader>
			<template v-if="tokenStr">
				<CardTitle>Accept your invite</CardTitle>
				<CardDescription>Choose a name and password to finish.</CardDescription>
			</template>
			<template v-else>
				<CardTitle>Invalid invite link</CardTitle>
				<CardDescription>This link is missing its token. Ask an admin to resend the invite.</CardDescription>
			</template>
		</CardHeader>
		<CardContent>
			<AcceptInviteForm v-if="tokenStr" :token="tokenStr" />

			<Button v-else variant="outline" class="w-full" as-child>
				<NuxtLink to="/auth/login">Back to sign in</NuxtLink>
			</Button>
		</CardContent>
	</AuthShell>
</template>
