// apps/console/app/(auth)/auth/reset/page.tsx
import type { Metadata } from 'next';
import { InvalidLink } from '@/features/auth/invalid-link';
import { ResetPasswordForm } from '@/features/auth/reset-password-form';
import { firstParam } from '@/lib/search-params';

export const metadata: Metadata = { title: 'Choose a new password' };

export default async function ResetPage({ searchParams }: PageProps<'/auth/reset'>) {
	const token = firstParam((await searchParams).token);
	if (!token)
		return (
			<InvalidLink
				title="Invalid reset link"
				description="This link is missing its token. Request a new one from the sign-in page."
				tagline="Reset links are single-use and expire after one hour."
				action={{ href: '/auth/forgot', label: 'Request a new link' }}
			/>
		);
	return <ResetPasswordForm token={token} />;
}

// apps/console/app/pages/auth/reset.vue
<script setup lang="ts">
definePageMeta({ layout: 'auth' });

const token = useRoute().query.token;
const tokenStr = typeof token === 'string' ? token : null;
</script>

<template>
	<AuthShell tagline="Choose a new password">
		<CardHeader>
			<template v-if="tokenStr">
				<CardTitle>Reset your password</CardTitle>
				<CardDescription>Choose a new password for your account.</CardDescription>
			</template>
			<template v-else>
				<CardTitle>Invalid reset link</CardTitle>
				<CardDescription>This link is missing its token. Request a new one from the sign-in page.</CardDescription>
			</template>
		</CardHeader>
		<CardContent>
			<ResetPasswordForm v-if="tokenStr" :token="tokenStr" />

			<Button v-else variant="outline" class="w-full" as-child>
				<NuxtLink to="/auth/forgot">Request a new link</NuxtLink>
			</Button>
		</CardContent>
	</AuthShell>
</template>
