// apps/console/app/components/auth/ForgotPasswordForm.vue
<script setup lang="ts">
import * as z from 'zod';

const api = useApi();
const submitted = ref(false);
const rootError = ref<string | null>(null);

const schema = z.object({
	email: z.string().min(1, 'Enter your email.').email('Enter a valid email address.')
});

const { form, isSubmitting } = useAppForm({
	schema,
	defaultValues: { email: '' },
	onSubmit: async ({ value }) => {
		rootError.value = null;
		try {
			await apiData(api.auth.forgotPassword.post(value));
			submitted.value = true;
		} catch {
			rootError.value = 'Could not reach the server — please try again.';
		}
	}
});
</script>

<template>
	<div v-if="submitted" class="flex flex-col gap-4">
		<p class="text-sm text-muted-subtle">If an account exists for that email, we've sent a link to reset your password. Check your inbox.</p>
		<Button variant="outline" class="w-full" as-child>
			<NuxtLink to="/auth/login">Back to sign in</NuxtLink>
		</Button>
	</div>
	<AppForm v-else :form="form" class="flex flex-col gap-4">
		<Field v-slot="{ componentField }" name="email" label="Email">
			<Input v-bind="componentField" type="email" autocomplete="email" autofocus placeholder="you@example.com" :disabled="isSubmitting" />
		</Field>

		<p v-if="rootError" role="alert" class="text-sm text-destructive">{{ rootError }}</p>

		<Button type="submit" class="mt-1 w-full" :disabled="isSubmitting">{{ isSubmitting ? 'Sending…' : 'Send reset link' }}</Button>
		<Button variant="ghost" class="w-full" as-child>
			<NuxtLink to="/auth/login">Back to sign in</NuxtLink>
		</Button>
	</AppForm>
</template>

// apps/console/features/auth/forgot-password-form.tsx
'use client';

import { apiData } from '@kubwave/api-client';
import { useForm } from '@tanstack/react-form';
import { ArrowLeftIcon, MailCheckIcon } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { toast } from 'sonner';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { getBrowserApi } from '@/lib/api/browser-api';
import { AuthCard, AuthNotice, FormError, FormField, SubmitButton } from './auth-kit';

const schema = z.object({ email: z.string().min(1, 'Enter your email.').email('Enter a valid email address.') });

const requestResetLink = (email: string) => apiData(getBrowserApi().auth.forgotPassword.post({ email }));

export function ForgotPasswordForm() {
	const [sentTo, setSentTo] = useState<string | null>(null);
	const [error, setError] = useState<string | null>(null);
	const form = useForm({
		defaultValues: { email: '' },
		validators: { onSubmit: schema },
		onSubmit: async ({ value }) => {
			setError(null);
			try {
				await requestResetLink(value.email);
				setSentTo(value.email);
			} catch {
				setError('Could not reach the server — please try again.');
			}
		}
	});

	if (sentTo) {
		return (
			<AuthCard tagline="Reset links expire after one hour.">
				<AuthNotice
					icon={<MailCheckIcon />}
					tone="primary"
					title="Check your inbox"
					description={
						<>
							If an account exists for <span className="font-mono text-foreground">{sentTo}</span>, you&apos;ll receive a link to reset your password.
						</>
					}
				>
					<Button asChild variant="outline">
						<Link href="/auth/login">Back to sign in</Link>
					</Button>
					<Button
						variant="ghost"
						size="sm"
						className="text-muted-foreground"
						onClick={() =>
							requestResetLink(sentTo).then(
								() => toast.success('Reset link sent again', { description: sentTo }),
								() => toast.error('Could not reach the server — please try again.')
							)
						}
					>
						Didn&apos;t get it? Resend
					</Button>
				</AuthNotice>
			</AuthCard>
		);
	}

	return (
		<AuthCard
			title="Reset your password"
			description="Enter the email you sign in with and we'll send you a reset link."
			tagline="Reset links expire after one hour."
			footer={
				<Link href="/auth/login" className="inline-flex items-center gap-1.5 transition-colors hover:text-foreground">
					<ArrowLeftIcon className="size-3.5" />
					Back to sign in
				</Link>
			}
		>
			<form
				noValidate
				onSubmit={event => {
					event.preventDefault();
					void form.handleSubmit();
				}}
				className="grid gap-4"
			>
				<form.Field name="email">
					{field => <FormField field={field} label="Email" type="email" autoComplete="email" placeholder="you@company.com" autoFocus />}
				</form.Field>
				<FormError message={error} />
				<form.Subscribe selector={state => state.isSubmitting}>
					{submitting => <SubmitButton pending={submitting}>Send reset link</SubmitButton>}
				</form.Subscribe>
			</form>
		</AuthCard>
	);
}
