// apps/console/app/components/auth/LoginForm.vue
<script setup lang="ts">
import * as z from 'zod';
import { setAccessToken } from '~/utils/token-store';

const api = useApi();
const user = useSessionUser();
const route = useRoute();
const rootError = ref<string | null>(null);
const justReset = computed(() => route.query.reset === '1');

const schema = z.object({
	email: z.string().min(1, 'Enter your email.').email('Enter a valid email address.'),
	password: z.string().min(1, 'Enter your password.')
});

const { form, isSubmitting } = useAppForm({
	schema,
	defaultValues: { email: '', password: '' },
	onSubmit: async ({ value }) => {
		rootError.value = null;
		try {
			const { accessToken } = await apiData(api.auth.login.post(value)).catch(err => {
				throw new Error(errorCode(err) === 'invalid_credentials' ? 'Invalid email or password.' : 'Something went wrong — please try again.');
			});
			setAccessToken(accessToken);
			const session = await apiData(api.auth.session.get()).catch(() => null);
			if (!session) {
				rootError.value = 'Signed in, but could not load your session.';
				return;
			}
			user.value = session.user;
			await navigateTo('/', { replace: true });
		} catch (err) {
			rootError.value = err instanceof Error ? err.message : 'Could not reach the server.';
		}
	}
});
</script>

<template>
	<AppForm :form="form" class="flex flex-col gap-4">
		<p v-if="justReset" class="text-sm text-muted-subtle">Your password was updated. Sign in with your new password.</p>
		<Field v-slot="{ componentField }" name="email" label="Email">
			<Input v-bind="componentField" type="email" autocomplete="email" autofocus placeholder="you@example.com" :disabled="isSubmitting" />
		</Field>
		<Field name="password" label="Password">
			<template #label-action>
				<NuxtLink to="/auth/forgot" class="text-sm font-medium text-primary-text hover:underline">Forgot password?</NuxtLink>
			</template>
			<template #default="{ componentField }">
				<Input v-bind="componentField" type="password" autocomplete="current-password" placeholder="••••••••" :disabled="isSubmitting" />
			</template>
		</Field>

		<p v-if="rootError" role="alert" class="text-sm text-destructive">{{ rootError }}</p>

		<Button type="submit" class="mt-1 w-full" :disabled="isSubmitting">{{ isSubmitting ? 'Signing in…' : 'Sign in' }}</Button>
	</AppForm>
</template>

// apps/console/features/auth/login-form.tsx
'use client';

import { apiData } from '@kubwave/api-client';
import { useForm } from '@tanstack/react-form';
import { CircleCheckIcon } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import * as z from 'zod';
import { getBrowserApi } from '@/lib/api/browser-api';
import { errorCode } from '@/lib/api/api-error';
import { AuthCard, FormError, FormField, SubmitButton } from './auth-kit';

const schema = z.object({
	email: z.string().min(1, 'Enter your email.').email('Enter a valid email address.'),
	password: z.string().min(1, 'Enter your password.')
});

export function LoginForm({ redirectTo, justReset }: { redirectTo: string; justReset: boolean }) {
	const [error, setError] = useState<string | null>(null);
	const form = useForm({
		defaultValues: { email: '', password: '' },
		validators: { onSubmit: schema },
		onSubmit: async ({ value }) => {
			setError(null);
			try {
				await apiData(getBrowserApi().auth.login.post(value));
				// A full load lets the proxy run the setup check and render with the new session.
				window.location.assign(redirectTo);
			} catch (err) {
				setError(errorCode(err) === 'invalid_credentials' ? 'Invalid email or password.' : 'Something went wrong — please try again.');
			}
		}
	});

	return (
		<AuthCard title="Sign in" footer="No account yet? Ask a team owner for an invite.">
			<form
				noValidate
				onSubmit={event => {
					event.preventDefault();
					void form.handleSubmit();
				}}
				className="grid gap-4"
			>
				{justReset && (
					<p className="flex items-start gap-2 rounded-md border border-success/30 bg-success/5 px-3 py-2 text-sm">
						<CircleCheckIcon className="mt-0.5 size-4 shrink-0 text-success" />
						Your password was updated. Sign in with your new password.
					</p>
				)}
				<form.Field name="email">
					{field => <FormField field={field} label="Email" type="email" autoComplete="email" placeholder="you@company.com" autoFocus />}
				</form.Field>
				<form.Field name="password">
					{field => (
						<FormField
							field={field}
							label="Password"
							type="password"
							autoComplete="current-password"
							aside={
								<Link href="/auth/forgot" className="text-xs text-muted-foreground transition-colors hover:text-foreground">
									Forgot password?
								</Link>
							}
						/>
					)}
				</form.Field>
				<FormError message={error} />
				<form.Subscribe selector={state => state.isSubmitting}>
					{submitting => (
						<SubmitButton pending={submitting} className="mt-2">
							Sign in
						</SubmitButton>
					)}
				</form.Subscribe>
			</form>
		</AuthCard>
	);
}
