// apps/console/app/components/base/StatTile.vue
<script setup lang="ts">
import type { Component } from 'vue';

// Icon + label + big tabular value. One tile for dashboard and admin stats so they can't drift.
defineProps<{ label: string; value: number | string; icon: Component; pending?: boolean }>();
</script>

<template>
	<div class="rounded-xl border bg-card p-4 shadow-xs">
		<span class="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
			<component :is="icon" class="size-4" />
			{{ label }}
		</span>
		<Skeleton v-if="pending" class="mt-2 h-8 w-10" />
		<p v-else class="mt-2 text-2xl font-semibold tabular-nums">{{ value }}</p>
	</div>
</template>

// apps/console/components/stat-tile.tsx
import { cn } from '@/lib/utils';

export function StatTile({
	label,
	value,
	hint,
	icon,
	className
}: {
	label: string;
	value: React.ReactNode;
	hint?: React.ReactNode;
	icon?: React.ReactNode;
	className?: string;
}) {
	return (
		<div className={cn('rounded-lg border bg-card p-4', className)}>
			<div className="flex items-center justify-between text-xs text-muted-foreground">
				{label}
				{icon}
			</div>
			<div className="mt-2 text-2xl font-semibold tracking-tight">{value}</div>
			{hint && <div className="mt-1 text-xs text-muted-foreground">{hint}</div>}
		</div>
	);
}
